### ISSUE TITLE
Refresh Issuee

### ISSUE THREAD

**Issue by SyedTahseen** [cheems/GDIndex#10]
Dude, it's design is cool. But it got refresh issue. Manytimes when we open folders, we need to refresh it everytime.

**Comment by cheems** [comment]
How did you create the code? By using quick deployment method mentioned in the readme.md or filling details manually by taking the code inside index.js?

**Comment by cheems** [comment]
Please use this: [index_beta.js](https://github.com/cheems/GDIndex/blob/master/index_beta.js) instead.

You can fill required fields manually by using previously generated data.
Or use quick deployment option to generate auth credentials.

When using the beta version, if you get any problems relevant to API limits, please reopen this issue.

**Comment by SyedTahseen** [comment]
okay brother, can you add a feature like we can search files from the whole drive like the official Google Drive app search files from shared drive too, rather than searching it from one shared drive to another, and upload feature like gdindex would be great to upload small files quicky.

**Comment by cheems** [comment]
Making the search function able to search across all drives is quite easy but once the search results are retrieved, file path should be created to the file, relative to the disk root. In this case, if the file that user tries to download is from another drive which is not included in the index, then a download url(a path which starts from the index root (ex: blahblah.workers.dev/path/file.txt)) cannot be created. But I still see some possibility to retrieve search results only from drives which are included in the index. But I have to study more about it before saying whether it can be done or not. 

When it comes to uploading option, only I have to say is the same thing I said regarding the global search option

**Comment by cheems** [comment]
Making the search function able to search across all drives is quite easy but once the search results are retrieved, file path should be created to the file, relative to the disk root. In this case, if the file that user tries to download is from another drive which is not included in the index, then a download url(a path which starts from the index root (ex: blahblah.workers.dev/path/file.txt)) cannot be created. But I still see some possibility to retrieve search results only from drives which are included in the index. But I have to study more about it before saying whether it can be done or not. 

When it comes to uploading option, the only thing I have to say is the same thing I said regarding the global search option

**Comment by SyedTahseen** [comment]
![Screenshot_20210912-210550](https://user-images.githubusercontent.com/53108646/133000382-64a07518-eee6-438f-8e59-6e9e82f3a4b4.png)
I found another issue, it isn't working in UC browser

**Comment by cheems** [comment]
It seems like they use kind of a content compressing method to enhance the UX which can cause issues. Also, the opensource icons used in this project doesn't provide any support for this browser so it may cause this issue also. Anyway I will have a look but it may take some time:3
