### ISSUE TITLE
Apply a usage rate limiting when downloading multiple files

### ISSUE THREAD

**Issue by JustThinker1** [cheems/GDIndex#12]
Hello,

Is it possible to add an option to apply a usage rate limiting when downloading multiple files?

For example: When someone download more than 3 files at the same time, The index will show a 403 error because of exceeding of usage rate limiting or something.

I think it would be good to avoid abusing of the public

Sincerely

**Comment by cheems** [comment]
I'm working on this but with a different approach. Thinking of adding service account support so we can minimize the effect of limits per user per time period.

But if you use your own API keys then you can also set a per user rate limit (by default 1000 requests per 100 sec) to prevent one user from depleting your app's quota. That's available in the "Quotas" tab
