### ISSUE TITLE
The indexer doesn't work on android's chrome

### ISSUE THREAD

**Issue by JustThinker1** [cheems/GDIndex#13]
Hi,

The indexer doesn't work on android's chrome, It just keep loading forever, although it works well on the laptop

Can you fix it?

**Comment by cheems** [comment]
I think you have faced the sane issue which is mentioned here: #10 

Please follow the first three replies. After you updated the code please use a private tab to check if updates are applied.

Also try the demo which is mentioned in the repo description and check if it works well. I just checked the demo with my phone and it works on Chrome without giving any issues
