### ISSUE TITLE
This is based on goindex not GDindex

### ISSUE THREAD

**Issue by askfriends** [cheems/GDIndex#3]
Kindly mention it clearly on what platform its built on?
you have mentioned GDindex but i guess its based on goindex, if its built on goindex than can you make it or create new repository for GDindex?
bcoz my bot requires GDindex and it doesnt work on goindex.
I really love this theme and wanna use it.
thanks

**Comment by cheems** [comment]
When I naming the repo, I just only thought of a short form of Google Drive Index but Completely forgot that there is another index named GDIndex. So I mentioned that this theme is based on goindex in the readme.md :)

**Comment by cheems** [comment]
When naming the repo, I just only thought of a short form of Google Drive Index but Completely forgot that there is another index named GDIndex. So I mentioned that this theme is based on goindex in the readme.md :)

**Comment by cheems** [comment]
When naming the repo, I just only thought of a short form of Google Drive Index and completely forgot that there is another index named GDIndex. So later I mentioned that this theme is based on goindex in the readme.md :)

**Comment by askfriends** [comment]
> When naming the repo, I just only thought of a short form of Google Drive Index and completely forgot that there is another index named GDIndex. So later I mentioned that this theme is based on goindex in the readme.md :)

thanks for the response.
btw can u make this with GDindex?
and also can u add dual audio support so that we can switch audio from the player?

**Comment by cheems** [comment]
The video/audio compatibility in browsers is limited, open it with the local player. Then it is possible to switch between audio tracks
