### ISSUE TITLE
[BUG] UI

### ISSUE THREAD

**Issue by xkoti** [cheems/GDIndex#30]
I noticed that when the folder/file name is too long the item view is messed up, also the directory is overlapping. And if I changed the color to different color the hover color of the directory tab is still blue.

Version: 1.3.6

![image](https://user-images.githubusercontent.com/80556958/138115852-10be129a-2314-4e50-a200-db2fb04f404b.png)

Suggestion: Create Todo list on readme to prevent feature  suggestion if already working on that feature.

I really hope that the video player is change to [Plyr](https://github.com/sampotts/plyr) in the next update, also updated icons

Regards

**Comment by cheems** [comment]
@xkoti 
Fixed. Hovever you will still find that navigation bar overlapping issue has not been fully fixed. But its effect has been minimized and now it doesn't cover the search icon.

You can find the updated index code from here: [goindex-extended/index_beta.js](https://github.com/cheems/goindex-extended/blob/master/index_beta.js).

Please have a look and confirm fixes are working. Then I can add them to the stable release.

Also, I will later try to do something more regarding the navigation bar.

Yes. Adding the todo list to the readme is also in the todo list. I will add it soon. ;-)
